import React, { useRef, useState } from 'react';
import './PlayGallery.css';

const GAMES = [
  { id:'01', slug:'last-order', genre:'POINT & CLICK', title:'LAST ORDER', korean:'라스트 오더', sub:'마감 이후, 도착한 마지막 주문', description:'비 오는 밤의 작은 카페. 조용한 공간을 살피고 단서를 찾아 마지막 손님의 주문을 완성하는 포인트 앤 클릭 방탈출입니다.', tags:['React','TypeScript','Puzzle Logic','Inventory'], image:'/assets/play-gallery/last-order.png', href:'https://last-order-1008.netlify.app/', feature:'OBSERVE', meta:'2026 · INTERACTIVE PUZZLE', highlight:'사물의 상태와 플레이어의 행동이 맞물리는, 작은 이야기의 공간.', learning:'행주로 창문을 닦거나 주문을 확인하는 행동이 다음 상호작용의 조건이 됩니다. 획득한 아이템과 진행 단계를 연결해, 플레이어에게 가능한 행동과 그 결과를 화면으로 전달했습니다.', skillSummary:'사물 클릭 · 조건부 렌더링 · 인벤토리 상태' },
  { id:'02', slug:'subway', genre:'SURVIVAL TRPG', title:'SUBWAY', korean:'사라진 다음 역', sub:'00:37 AM, 사라진 다음 역', description:'정차한 심야 지하철에서 시작되는 생존 탐사. 제한된 조사 기회, D20 판정, 아이템과 단서가 후속 선택에 영향을 주는 분기형 게임입니다.', tags:['React','useReducer','D20 System','State Machine'], image:'/assets/play-gallery/subway.webp', href:'https://subway-trpg.vercel.app/', feature:'SURVIVE', meta:'2026 · SURVIVAL NARRATIVE', highlight:'무엇을 조사했는가에 따라 달라지는 이후의 결과.', learning:'조사 횟수와 아이템, 이전에 발견한 단서를 게임 상태로 관리합니다. useReducer 기반 흐름에서 선택에 따라 후속 판정과 화면이 달라지도록 구성해 복잡한 분기 로직을 다뤘습니다.', skillSummary:'useReducer · 상태 분기 · 확률 판정' },
  { id:'03', slug:'signal', genre:'NARRATIVE TRPG', title:'NO SIGNAL', korean:'귀환 신호 없음', sub:'돌아오지 않는 두 조사관의 기록', description:'통신이 끊긴 연구시설. D100 주사위 판정과 동료의 자율 행동, 시네마틱 Canvas 연출로 구성한 짧은 서사형 탐사 데모입니다.', tags:['React','TypeScript','D100 System','Canvas FX'], image:'/assets/play-gallery/signal.webp', href:'https://no-signal-1008.netlify.app/', feature:'INVESTIGATE', meta:'2026 · TEXT-LOG EXPERIMENT', highlight:'같은 상황을 마주한 두 인물은 서로 다른 선택을 한다.', learning:'시나리오 데이터를 화면 표시 로직과 분리하고, D100 판정 및 동료 행동 결과에 따라 서로 다른 텍스트와 시각 효과를 제공합니다. 선택의 결과를 읽는 경험까지 인터페이스로 설계했습니다.', skillSummary:'데이터 중심 시나리오 · D100 판정 · Canvas 효과' },
  { id:'04', slug:'brick', genre:'VANILLA JS / CANVAS', title:'NEON BREAK', korean:'도전! 벽돌깨기', sub:'처음 만들어 본, 작고 반짝이는 게임', description:'프론트엔드 학습 초기에 제작한 Vanilla JavaScript 벽돌깨기. Canvas 충돌 판정과 난이도별 네온 테마, Web Audio API로 만든 8비트 효과음을 직접 구현한 레트로 아케이드 게임입니다.', tags:['Vanilla JS','Canvas API','Web Audio API','Collision'], image:null, href:'https://guileless-sopapillas-65ec2b.netlify.app/', feature:'BREAK', meta:'EARLY STUDY · ARCADE GAME', highlight:'작은 공 하나를 움직이던 때부터 시작된 인터랙션 실험.', learning:'공·패들·벽돌을 Canvas에 매 프레임 다시 그리고 충돌 시 방향을 계산했습니다. 난이도별 속도와 화면 테마, Web Audio API 효과음을 직접 연결한 바닐라 JS 초기 실습작입니다.', skillSummary:'Canvas 2D · requestAnimationFrame · 입력·충돌 처리' },
];

function BrickArtwork(){return <div className="brick-art" aria-hidden="true"><span className="brick-top">NEON / ARCADE</span><div className="brick-wall">{Array.from({length:24},(_,i)=><i key={i} style={{'--n':i%4}} />)}</div><div className="brick-motion"><div className="brick-ball"/></div><div className="brick-paddle"/><span className="brick-bottom">INSERT COIN · PLAY</span></div>}
function GameTile({game,active,onSelect}){return <button className={`tile tile-${game.slug} ${active?'selected':''}`} type="button" onClick={onSelect} aria-pressed={active} aria-label={`${game.title} 프로젝트 상세 보기`}><span className="tile-image">{game.image?<img src={game.image} alt="" loading="lazy"/>:<BrickArtwork/>}</span><span className="tile-num">{game.id} / {game.feature}</span><span className="tile-content"><small>{game.genre}</small><strong>{game.title}</strong></span><span className="tile-north" aria-hidden="true">↗</span></button>}
export default function PlayGallery(){
  const [selected,setSelected]=useState('01');const detailRef=useRef(null);const game=GAMES.find(g=>g.id===selected)||GAMES[0];
  const selectGame=(id)=>{setSelected(id);if(typeof window!=='undefined' && window.matchMedia('(max-width: 900px)').matches){window.requestAnimationFrame(()=>detailRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));}};
  return <div className="playGallery"><div className="play-shell" id="play"><div className="top-rule"><span><span className="asterisk">✳</span> YOOJIN'S INTERACTIVE ARCHIVE</span><span>FRONTEND PLAYGROUND &nbsp; / &nbsp; 2026</span></div><header className="heading"><div className="heading-title"><span className="eyebrow">04 PROJECTS &nbsp; · &nbsp; SELECTED EXPERIMENTS</span><h2 id="experiments-title">PLAY<span>.</span></h2></div><div className="heading-copy"><p>선택이 상태를 바꾸고, 그 변화가 화면에 드러나는 순간.</p><p>게임을 통해 입력 처리와 조건부 렌더링, 인터랙션을 실험했습니다.</p><span className="hand-note">Made to be explored ↗</span></div></header>
  <section className="gallery" aria-label="프로젝트 선택 및 상세 설명"><div className="mosaic">{GAMES.map(g=><GameTile key={g.id} game={g} active={selected===g.id} onSelect={()=>selectGame(g.id)}/>)}</div><article className="detail" ref={detailRef} aria-live="polite" tabIndex="-1"><div className="detail-top"><span>PROJECT {game.id} / 04</span><span className="detail-line"/><span>{game.genre}</span></div><div className="detail-body" key={game.id} tabIndex="0" aria-label={`${game.title} 상세 설명`}><p className="detail-kicker">{game.meta}</p><h3>{game.title}</h3><p className="detail-sub">{game.sub}</p><div className="detail-quote">“{game.highlight}”</div><p className="detail-description">{game.description}</p><div className="frontend-note"><span>FRONTEND IMPLEMENTATION</span><p>{game.learning}</p><p className="skill-summary">{game.skillSummary}</p></div><div className="tag-title">BUILT WITH</div><div className="tags">{game.tags.map(t=><span key={t}>{t}</span>)}</div></div><div className="detail-cta"><a className="launch" href={game.href} target="_blank" rel="noopener noreferrer">게임 플레이하기 <span>↗</span></a><span className="detail-footnote">{game.slug==='brick'?'ORIGINAL: VANILLA JAVASCRIPT': 'EXPLORE / EXPERIMENT / CREATE'}</span></div></article></section>
  <footer className="footer"><nav aria-label="작품 빠른 탐색">{GAMES.map(g=><button type="button" key={g.id} className={selected===g.id?'current':''} onClick={()=>selectGame(g.id)} aria-current={selected===g.id?'true':undefined}><span>{g.id}</span>{g.title}</button>)}</nav><p>IMAGINATION, MEET INTERACTION. <span>© 2026 YOOJIN</span></p></footer></div></div>
}
